### ISSUE TITLE
`'title': undefined method 'inject' for nil:NilClass (NoMethodError)`

### ISSUE THREAD

**Issue by moloch--** [emoriarty/jekyll-notion#64]
```
/opt/homebrew/lib/ruby/gems/3.2.0/gems/notion_to_md-2.2.1/lib/notion_to_md/page.rb:13:in `title': undefined method `inject' for nil:NilClass (NoMethodError)

      page.dig(:properties, :Name, :title).inject('') do |acc, slug|
                                          ^^^^^^^
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-notion-2.3.2/lib/jekyll-notion/generators/page_generator.rb:16:in `make_page'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-notion-2.3.2/lib/jekyll-notion/generators/page_generator.rb:8:in `generate'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-notion-2.3.2/lib/jekyll-notion/generator.rb:67:in `block in read_notion_pages'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-notion-2.3.2/lib/jekyll-notion/generator.rb:65:in `each'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-notion-2.3.2/lib/jekyll-notion/generator.rb:65:in `read_notion_pages'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/jekyll-notion-2.3.2/lib/jekyll-notion/generator.rb:14:in `generate'
```

**Comment by emoriarty** [comment]
Hello @moloch-- ,

Thanks for submitting an issue.

Could you share some context? I am trying to reproduce it but with no luck.

**Comment by emoriarty** [comment]
Found it!
```bash
/Users/enriquearias/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/notion_to_md-2.2.2/lib/notion_to_md/page.rb:13:in `title': undefined method `inject' for nil:NilClass (NoMethodError)
```
The problem occurs when the page is brand new and no template has been chosen yet. 

<img width="500" alt="Screen Shot 2023-02-16 at 09 21 46" src="https://user-images.githubusercontent.com/510375/219308152-b6ff80b2-c1a1-4d1a-b6a4-0e801c8f66ce.png">

In this case, the property where the `title` is usually found, is not in the same "path". According to the API docs, usually the property title has the following structure:
```json
{
  "Name": {
    "title": [
      {
        "type": "text",
        "text": {
          "content": "The title"
        }
      }
    ]
  }
}
```
But, when the page is in this pristine state, the title property has this other structure:
```json
{
  "title": {
    "title": [
      {
        "type": "rich_text",
        "rich_text": {
          "content": "The title"
        }
      }
    ]
  }
}
```
I have not found specific information on the matter but between the test I have done and the information in the [doc](https://developers.notion.com/reference/property-value-object#title-property-values), I have assumed how it works.

I'm going to work for a fix. Even if it is no usual having without content and a title, this can happen and should not prevent the site being build.

I will also improve the treatment of pages that do not have a title: they will probably not be built and will be logged with a warning.

Thanks again for spotting the error 👍
